package com.windsor.fuckCn2b2t;

final class I11I {

    private I11I() {
    }

    private static final String lllI =
            "aaa\n" +
            "aarp\n" +
            "abb\n" +
            "abbott\n" +
            "abbvie\n" +
            "abc\n" +
            "able\n" +
            "abogado\n" +
            "abudhabi\n" +
            "ac\n" +
            "academy\n" +
            "accenture\n" +
            "accountant\n" +
            "accountants\n" +
            "aco\n" +
            "actor\n" +
            "ad\n" +
            "ads\n" +
            "adult\n" +
            "ae\n" +
            "aeg\n" +
            "aero\n" +
            "aetna\n" +
            "af\n" +
            "afl\n" +
            "africa\n" +
            "ag\n" +
            "agakhan\n" +
            "agency\n" +
            "ai\n" +
            "aig\n" +
            "airbus\n" +
            "airforce\n" +
            "airtel\n" +
            "akdn\n" +
            "al\n" +
            "alibaba\n" +
            "alipay\n" +
            "allfinanz\n" +
            "allstate\n" +
            "ally\n" +
            "alsace\n" +
            "alstom\n" +
            "am\n" +
            "amazon\n" +
            "americanexpress\n" +
            "americanfamily\n" +
            "amex\n" +
            "amfam\n" +
            "amica\n" +
            "amsterdam\n" +
            "analytics\n" +
            "android\n" +
            "anquan\n" +
            "anz\n" +
            "ao\n" +
            "aol\n" +
            "apartments\n" +
            "app\n" +
            "apple\n" +
            "aq\n" +
            "aquarelle\n" +
            "ar\n" +
            "arab\n" +
            "aramco\n" +
            "archi\n" +
            "army\n" +
            "arpa\n" +
            "art\n" +
            "arte\n" +
            "as\n" +
            "asda\n" +
            "asia\n" +
            "associates\n" +
            "at\n" +
            "athleta\n" +
            "attorney\n" +
            "au\n" +
            "auction\n" +
            "audi\n" +
            "audible\n" +
            "audio\n" +
            "auspost\n" +
            "author\n" +
            "auto\n" +
            "autos\n" +
            "aw\n" +
            "aws\n" +
            "ax\n" +
            "axa\n" +
            "az\n" +
            "azure\n" +
            "ba\n" +
            "baby\n" +
            "baidu\n" +
            "banamex\n" +
            "band\n" +
            "bank\n" +
            "bar\n" +
            "barcelona\n" +
            "barclaycard\n" +
            "barclays\n" +
            "barefoot\n" +
            "bargains\n" +
            "baseball\n" +
            "basketball\n" +
            "bauhaus\n" +
            "bayern\n" +
            "bb\n" +
            "bbc\n" +
            "bbt\n" +
            "bbva\n" +
            "bcg\n" +
            "bcn\n" +
            "bd\n" +
            "be\n" +
            "beats\n" +
            "beauty\n" +
            "beer\n" +
            "berlin\n" +
            "best\n" +
            "bestbuy\n" +
            "bet\n" +
            "bf\n" +
            "bg\n" +
            "bh\n" +
            "bharti\n" +
            "bi\n" +
            "bible\n" +
            "bid\n" +
            "bike\n" +
            "bing\n" +
            "bingo\n" +
            "bio\n" +
            "biz\n" +
            "bj\n" +
            "black\n" +
            "blackfriday\n" +
            "blockbuster\n" +
            "blog\n" +
            "bloomberg\n" +
            "blue\n" +
            "bm\n" +
            "bms\n" +
            "bmw\n" +
            "bn\n" +
            "bnpparibas\n" +
            "bo\n" +
            "boats\n" +
            "boehringer\n" +
            "bofa\n" +
            "bom\n" +
            "bond\n" +
            "boo\n" +
            "book\n" +
            "booking\n" +
            "bosch\n" +
            "bostik\n" +
            "boston\n" +
            "bot\n" +
            "boutique\n" +
            "box\n" +
            "br\n" +
            "bradesco\n" +
            "bridgestone\n" +
            "broadway\n" +
            "broker\n" +
            "brother\n" +
            "brussels\n" +
            "bs\n" +
            "bt\n" +
            "build\n" +
            "builders\n" +
            "business\n" +
            "buy\n" +
            "buzz\n" +
            "bv\n" +
            "bw\n" +
            "by\n" +
            "bz\n" +
            "bzh\n" +
            "ca\n" +
            "cab\n" +
            "cafe\n" +
            "cal\n" +
            "call\n" +
            "calvinklein\n" +
            "cam\n" +
            "camera\n" +
            "camp\n" +
            "canon\n" +
            "capetown\n" +
            "capital\n" +
            "capitalone\n" +
            "car\n" +
            "caravan\n" +
            "cards\n" +
            "care\n" +
            "career\n" +
            "careers\n" +
            "cars\n" +
            "casa\n" +
            "case\n" +
            "cash\n" +
            "casino\n" +
            "cat\n" +
            "catering\n" +
            "catholic\n" +
            "cba\n" +
            "cbn\n" +
            "cbre\n" +
            "cc\n" +
            "cd\n" +
            "center\n" +
            "ceo\n" +
            "cern\n" +
            "cf\n" +
            "cfa\n" +
            "cfd\n" +
            "cg\n" +
            "ch\n" +
            "chanel\n" +
            "channel\n" +
            "charity\n" +
            "chase\n" +
            "chat\n" +
            "cheap\n" +
            "chintai\n" +
            "christmas\n" +
            "chrome\n" +
            "church\n" +
            "ci\n" +
            "cipriani\n" +
            "circle\n" +
            "cisco\n" +
            "citadel\n" +
            "citi\n" +
            "citic\n" +
            "city\n" +
            "ck\n" +
            "cl\n" +
            "claims\n" +
            "cleaning\n" +
            "click\n" +
            "clinic\n" +
            "clinique\n" +
            "clothing\n" +
            "cloud\n" +
            "club\n" +
            "clubmed\n" +
            "cm\n" +
            "cn\n" +
            "co\n" +
            "coach\n" +
            "codes\n" +
            "coffee\n" +
            "college\n" +
            "cologne\n" +
            "com\n" +
            "commbank\n" +
            "community\n" +
            "company\n" +
            "compare\n" +
            "computer\n" +
            "comsec\n" +
            "condos\n" +
            "construction\n" +
            "consulting\n" +
            "contact\n" +
            "contractors\n" +
            "cooking\n" +
            "cool\n" +
            "coop\n" +
            "corsica\n" +
            "country\n" +
            "coupon\n" +
            "coupons\n" +
            "courses\n" +
            "cpa\n" +
            "cr\n" +
            "credit\n" +
            "creditcard\n" +
            "creditunion\n" +
            "cricket\n" +
            "crown\n" +
            "crs\n" +
            "cruise\n" +
            "cruises\n" +
            "cu\n" +
            "cuisinella\n" +
            "cv\n" +
            "cw\n" +
            "cx\n" +
            "cy\n" +
            "cymru\n" +
            "cyou\n" +
            "cz\n" +
            "dad\n" +
            "dance\n" +
            "data\n" +
            "date\n" +
            "dating\n" +
            "datsun\n" +
            "day\n" +
            "dclk\n" +
            "dds\n" +
            "de\n" +
            "deal\n" +
            "dealer\n" +
            "deals\n" +
            "degree\n" +
            "delivery\n" +
            "dell\n" +
            "deloitte\n" +
            "delta\n" +
            "democrat\n" +
            "dental\n" +
            "dentist\n" +
            "desi\n" +
            "design\n" +
            "dev\n" +
            "dhl\n" +
            "diamonds\n" +
            "diet\n" +
            "digital\n" +
            "direct\n" +
            "directory\n" +
            "discount\n" +
            "discover\n" +
            "dish\n" +
            "diy\n" +
            "dj\n" +
            "dk\n" +
            "dm\n" +
            "dnp\n" +
            "do\n" +
            "docs\n" +
            "doctor\n" +
            "dog\n" +
            "domains\n" +
            "dot\n" +
            "download\n" +
            "drive\n" +
            "dtv\n" +
            "dubai\n" +
            "dupont\n" +
            "durban\n" +
            "dvag\n" +
            "dvr\n" +
            "dz\n" +
            "earth\n" +
            "eat\n" +
            "ec\n" +
            "eco\n" +
            "edeka\n" +
            "edu\n" +
            "education\n" +
            "ee\n" +
            "eg\n" +
            "email\n" +
            "emerck\n" +
            "energy\n" +
            "engineer\n" +
            "engineering\n" +
            "enterprises\n" +
            "epson\n" +
            "equipment\n" +
            "er\n" +
            "ericsson\n" +
            "erni\n" +
            "es\n" +
            "esq\n" +
            "estate\n" +
            "et\n" +
            "eu\n" +
            "eurovision\n" +
            "eus\n" +
            "events\n" +
            "exchange\n" +
            "expert\n" +
            "exposed\n" +
            "express\n" +
            "extraspace\n" +
            "fage\n" +
            "fail\n" +
            "fairwinds\n" +
            "faith\n" +
            "family\n" +
            "fan\n" +
            "fans\n" +
            "farm\n" +
            "farmers\n" +
            "fashion\n" +
            "fast\n" +
            "fedex\n" +
            "feedback\n" +
            "ferrari\n" +
            "ferrero\n" +
            "fi\n" +
            "fidelity\n" +
            "fido\n" +
            "film\n" +
            "final\n" +
            "finance\n" +
            "financial\n" +
            "fire\n" +
            "firestone\n" +
            "firmdale\n" +
            "fish\n" +
            "fishing\n" +
            "fit\n" +
            "fitness\n" +
            "fj\n" +
            "fk\n" +
            "flickr\n" +
            "flights\n" +
            "flir\n" +
            "florist\n" +
            "flowers\n" +
            "fly\n" +
            "fm\n" +
            "fo\n" +
            "foo\n" +
            "food\n" +
            "football\n" +
            "ford\n" +
            "forex\n" +
            "forsale\n" +
            "forum\n" +
            "foundation\n" +
            "fox\n" +
            "fr\n" +
            "free\n" +
            "fresenius\n" +
            "frl\n" +
            "frogans\n" +
            "frontier\n" +
            "ftr\n" +
            "fujitsu\n" +
            "fun\n" +
            "fund\n" +
            "furniture\n" +
            "futbol\n" +
            "fyi\n" +
            "ga\n" +
            "gal\n" +
            "gallery\n" +
            "gallo\n" +
            "gallup\n" +
            "game\n" +
            "games\n" +
            "gap\n" +
            "garden\n" +
            "gay\n" +
            "gb\n" +
            "gbiz\n" +
            "gd\n" +
            "gdn\n" +
            "ge\n" +
            "gea\n" +
            "gent\n" +
            "genting\n" +
            "george\n" +
            "gf\n" +
            "gg\n" +
            "ggee\n" +
            "gh\n" +
            "gi\n" +
            "gift\n" +
            "gifts\n" +
            "gives\n" +
            "giving\n" +
            "gl\n" +
            "glass\n" +
            "gle\n" +
            "global\n" +
            "globo\n" +
            "gm\n" +
            "gmail\n" +
            "gmbh\n" +
            "gmo\n" +
            "gmx\n" +
            "gn\n" +
            "godaddy\n" +
            "gold\n" +
            "goldpoint\n" +
            "golf\n" +
            "goodyear\n" +
            "goog\n" +
            "google\n" +
            "gop\n" +
            "got\n" +
            "gov\n" +
            "gp\n" +
            "gq\n" +
            "gr\n" +
            "grainger\n" +
            "graphics\n" +
            "gratis\n" +
            "green\n" +
            "gripe\n" +
            "grocery\n" +
            "group\n" +
            "gs\n" +
            "gt\n" +
            "gu\n" +
            "gucci\n" +
            "guge\n" +
            "guide\n" +
            "guitars\n" +
            "guru\n" +
            "gw\n" +
            "gy\n" +
            "hair\n" +
            "hamburg\n" +
            "hangout\n" +
            "haus\n" +
            "hbo\n" +
            "hdfc\n" +
            "hdfcbank\n" +
            "health\n" +
            "healthcare\n" +
            "help\n" +
            "helsinki\n" +
            "here\n" +
            "hermes\n" +
            "hiphop\n" +
            "hisamitsu\n" +
            "hitachi\n" +
            "hiv\n" +
            "hk\n" +
            "hkt\n" +
            "hm\n" +
            "hn\n" +
            "hockey\n" +
            "holdings\n" +
            "holiday\n" +
            "homedepot\n" +
            "homegoods\n" +
            "homes\n" +
            "homesense\n" +
            "honda\n" +
            "horse\n" +
            "hospital\n" +
            "host\n" +
            "hosting\n" +
            "hot\n" +
            "hotels\n" +
            "hotmail\n" +
            "house\n" +
            "how\n" +
            "hr\n" +
            "hsbc\n" +
            "ht\n" +
            "hu\n" +
            "hughes\n" +
            "hyatt\n" +
            "hyundai\n" +
            "ibm\n" +
            "icbc\n" +
            "ice\n" +
            "icu\n" +
            "id\n" +
            "ie\n" +
            "ieee\n" +
            "ifm\n" +
            "ikano\n" +
            "il\n" +
            "im\n" +
            "imamat\n" +
            "imdb\n" +
            "immo\n" +
            "immobilien\n" +
            "in\n" +
            "inc\n" +
            "industries\n" +
            "infiniti\n" +
            "info\n" +
            "ing\n" +
            "ink\n" +
            "institute\n" +
            "insurance\n" +
            "insure\n" +
            "int\n" +
            "international\n" +
            "intuit\n" +
            "investments\n" +
            "io\n" +
            "ipiranga\n" +
            "iq\n" +
            "ir\n" +
            "irish\n" +
            "is\n" +
            "ismaili\n" +
            "ist\n" +
            "istanbul\n" +
            "it\n" +
            "itau\n" +
            "itv\n" +
            "jaguar\n" +
            "java\n" +
            "jcb\n" +
            "je\n" +
            "jeep\n" +
            "jetzt\n" +
            "jewelry\n" +
            "jio\n" +
            "jll\n" +
            "jm\n" +
            "jmp\n" +
            "jnj\n" +
            "jo\n" +
            "jobs\n" +
            "joburg\n" +
            "jot\n" +
            "joy\n" +
            "jp\n" +
            "jpmorgan\n" +
            "jprs\n" +
            "juegos\n" +
            "kaufen\n" +
            "kddi\n" +
            "ke\n" +
            "kerryhotels\n" +
            "kerryproperties\n" +
            "kfh\n" +
            "kg\n" +
            "kh\n" +
            "ki\n" +
            "kia\n" +
            "kids\n" +
            "kim\n" +
            "kindle\n" +
            "kitchen\n" +
            "kiwi\n" +
            "km\n" +
            "kn\n" +
            "koeln\n" +
            "komatsu\n" +
            "kosher\n" +
            "kp\n" +
            "kpmg\n" +
            "kpn\n" +
            "kr\n" +
            "krd\n" +
            "kred\n" +
            "kuokgroup\n" +
            "kw\n" +
            "ky\n" +
            "kyoto\n" +
            "kz\n" +
            "la\n" +
            "lacaixa\n" +
            "lamborghini\n" +
            "lamer\n" +
            "land\n" +
            "landrover\n" +
            "lanxess\n" +
            "lasalle\n" +
            "lat\n" +
            "latino\n" +
            "latrobe\n" +
            "law\n" +
            "lawyer\n" +
            "lb\n" +
            "lc\n" +
            "lds\n" +
            "lease\n" +
            "leclerc\n" +
            "lefrak\n" +
            "legal\n" +
            "lego\n" +
            "lexus\n" +
            "lgbt\n" +
            "li\n" +
            "lidl\n" +
            "life\n" +
            "lifeinsurance\n" +
            "lifestyle\n" +
            "lighting\n" +
            "like\n" +
            "lilly\n" +
            "limited\n" +
            "limo\n" +
            "lincoln\n" +
            "link\n" +
            "live\n" +
            "living\n" +
            "lk\n" +
            "llc\n" +
            "llp\n" +
            "loan\n" +
            "loans\n" +
            "locker\n" +
            "locus\n" +
            "lol\n" +
            "london\n" +
            "lotte\n" +
            "lotto\n" +
            "love\n" +
            "lpl\n" +
            "lplfinancial\n" +
            "lr\n" +
            "ls\n" +
            "lt\n" +
            "ltd\n" +
            "ltda\n" +
            "lu\n" +
            "lundbeck\n" +
            "luxe\n" +
            "luxury\n" +
            "lv\n" +
            "ly\n" +
            "ma\n" +
            "madrid\n" +
            "maif\n" +
            "maison\n" +
            "makeup\n" +
            "man\n" +
            "management\n" +
            "mango\n" +
            "map\n" +
            "market\n" +
            "marketing\n" +
            "markets\n" +
            "marriott\n" +
            "marshalls\n" +
            "mattel\n" +
            "mba\n" +
            "mc\n" +
            "mckinsey\n" +
            "md\n" +
            "me\n" +
            "med\n" +
            "media\n" +
            "meet\n" +
            "melbourne\n" +
            "meme\n" +
            "memorial\n" +
            "men\n" +
            "menu\n" +
            "merck\n" +
            "merckmsd\n" +
            "mg\n" +
            "mh\n" +
            "miami\n" +
            "microsoft\n" +
            "mil\n" +
            "mini\n" +
            "mint\n" +
            "mit\n" +
            "mitsubishi\n" +
            "mk\n" +
            "ml\n" +
            "mlb\n" +
            "mls\n" +
            "mm\n" +
            "mma\n" +
            "mn\n" +
            "mo\n" +
            "mobi\n" +
            "mobile\n" +
            "moda\n" +
            "moe\n" +
            "moi\n" +
            "mom\n" +
            "monash\n" +
            "money\n" +
            "monster\n" +
            "mormon\n" +
            "mortgage\n" +
            "moscow\n" +
            "moto\n" +
            "motorcycles\n" +
            "mov\n" +
            "movie\n" +
            "mp\n" +
            "mq\n" +
            "mr\n" +
            "ms\n" +
            "msd\n" +
            "mt\n" +
            "mtn\n" +
            "mtr\n" +
            "mu\n" +
            "museum\n" +
            "music\n" +
            "mv\n" +
            "mw\n" +
            "mx\n" +
            "my\n" +
            "mz\n" +
            "na\n" +
            "nab\n" +
            "nagoya\n" +
            "name\n" +
            "navy\n" +
            "nba\n" +
            "nc\n" +
            "ne\n" +
            "nec\n" +
            "net\n" +
            "netbank\n" +
            "netflix\n" +
            "network\n" +
            "neustar\n" +
            "new\n" +
            "news\n" +
            "next\n" +
            "nextdirect\n" +
            "nexus\n" +
            "nf\n" +
            "nfl\n" +
            "ng\n" +
            "ngo\n" +
            "nhk\n" +
            "ni\n" +
            "nico\n" +
            "nike\n" +
            "nikon\n" +
            "ninja\n" +
            "nissan\n" +
            "nissay\n" +
            "nl\n" +
            "no\n" +
            "nokia\n" +
            "norton\n" +
            "now\n" +
            "nowruz\n" +
            "nowtv\n" +
            "np\n" +
            "nr\n" +
            "nra\n" +
            "nrw\n" +
            "ntt\n" +
            "nu\n" +
            "nyc\n" +
            "nz\n" +
            "obi\n" +
            "observer\n" +
            "office\n" +
            "okinawa\n" +
            "olayan\n" +
            "olayangroup\n" +
            "ollo\n" +
            "om\n" +
            "omega\n" +
            "one\n" +
            "ong\n" +
            "onl\n" +
            "online\n" +
            "ooo\n" +
            "open\n" +
            "oracle\n" +
            "orange\n" +
            "org\n" +
            "organic\n" +
            "origins\n" +
            "osaka\n" +
            "otsuka\n" +
            "ott\n" +
            "ovh\n" +
            "pa\n" +
            "page\n" +
            "panasonic\n" +
            "paris\n" +
            "pars\n" +
            "partners\n" +
            "parts\n" +
            "party\n" +
            "pay\n" +
            "pccw\n" +
            "pe\n" +
            "pet\n" +
            "pf\n" +
            "pfizer\n" +
            "pg\n" +
            "ph\n" +
            "pharmacy\n" +
            "phd\n" +
            "philips\n" +
            "phone\n" +
            "photo\n" +
            "photography\n" +
            "photos\n" +
            "physio\n" +
            "pics\n" +
            "pictet\n" +
            "pictures\n" +
            "pid\n" +
            "pin\n" +
            "ping\n" +
            "pink\n" +
            "pioneer\n" +
            "pizza\n" +
            "pk\n" +
            "pl\n" +
            "place\n" +
            "play\n" +
            "playstation\n" +
            "plumbing\n" +
            "plus\n" +
            "pm\n" +
            "pn\n" +
            "pnc\n" +
            "pohl\n" +
            "poker\n" +
            "politie\n" +
            "porn\n" +
            "post\n" +
            "pr\n" +
            "praxi\n" +
            "press\n" +
            "prime\n" +
            "pro\n" +
            "prod\n" +
            "productions\n" +
            "prof\n" +
            "progressive\n" +
            "promo\n" +
            "properties\n" +
            "property\n" +
            "protection\n" +
            "pru\n" +
            "prudential\n" +
            "ps\n" +
            "pt\n" +
            "pub\n" +
            "pw\n" +
            "pwc\n" +
            "py\n" +
            "qa\n" +
            "qpon\n" +
            "quebec\n" +
            "quest\n" +
            "racing\n" +
            "radio\n" +
            "re\n" +
            "read\n" +
            "realestate\n" +
            "realtor\n" +
            "realty\n" +
            "recipes\n" +
            "red\n" +
            "redumbrella\n" +
            "rehab\n" +
            "reise\n" +
            "reisen\n" +
            "reit\n" +
            "reliance\n" +
            "ren\n" +
            "rent\n" +
            "rentals\n" +
            "repair\n" +
            "report\n" +
            "republican\n" +
            "rest\n" +
            "restaurant\n" +
            "review\n" +
            "reviews\n" +
            "rexroth\n" +
            "rich\n" +
            "richardli\n" +
            "ricoh\n" +
            "ril\n" +
            "rio\n" +
            "rip\n" +
            "ro\n" +
            "rocks\n" +
            "rodeo\n" +
            "rogers\n" +
            "room\n" +
            "rs\n" +
            "rsvp\n" +
            "ru\n" +
            "rugby\n" +
            "ruhr\n" +
            "run\n" +
            "rw\n" +
            "rwe\n" +
            "ryukyu\n" +
            "sa\n" +
            "saarland\n" +
            "safe\n" +
            "safety\n" +
            "sakura\n" +
            "sale\n" +
            "salon\n" +
            "samsclub\n" +
            "samsung\n" +
            "sandvik\n" +
            "sandvikcoromant\n" +
            "sanofi\n" +
            "sap\n" +
            "sarl\n" +
            "sas\n" +
            "save\n" +
            "saxo\n" +
            "sb\n" +
            "sbi\n" +
            "sbs\n" +
            "sc\n" +
            "scb\n" +
            "schaeffler\n" +
            "schmidt\n" +
            "scholarships\n" +
            "school\n" +
            "schule\n" +
            "schwarz\n" +
            "science\n" +
            "scot\n" +
            "sd\n" +
            "se\n" +
            "search\n" +
            "seat\n" +
            "secure\n" +
            "security\n" +
            "seek\n" +
            "select\n" +
            "sener\n" +
            "services\n" +
            "seven\n" +
            "sew\n" +
            "sex\n" +
            "sexy\n" +
            "sfr\n" +
            "sg\n" +
            "sh\n" +
            "shangrila\n" +
            "sharp\n" +
            "shell\n" +
            "shia\n" +
            "shiksha\n" +
            "shoes\n" +
            "shop\n" +
            "shopping\n" +
            "shouji\n" +
            "show\n" +
            "si\n" +
            "silk\n" +
            "sina\n" +
            "singles\n" +
            "site\n" +
            "sj\n" +
            "sk\n" +
            "ski\n" +
            "skin\n" +
            "sky\n" +
            "skype\n" +
            "sl\n" +
            "sling\n" +
            "sm\n" +
            "smart\n" +
            "smile\n" +
            "sn\n" +
            "sncf\n" +
            "so\n" +
            "soccer\n" +
            "social\n" +
            "softbank\n" +
            "software\n" +
            "sohu\n" +
            "solar\n" +
            "solutions\n" +
            "song\n" +
            "sony\n" +
            "soy\n" +
            "spa\n" +
            "space\n" +
            "sport\n" +
            "spot\n" +
            "sr\n" +
            "srl\n" +
            "ss\n" +
            "st\n" +
            "stada\n" +
            "staples\n" +
            "star\n" +
            "statebank\n" +
            "statefarm\n" +
            "stc\n" +
            "stcgroup\n" +
            "stockholm\n" +
            "storage\n" +
            "store\n" +
            "stream\n" +
            "studio\n" +
            "study\n" +
            "style\n" +
            "su\n" +
            "sucks\n" +
            "supplies\n" +
            "supply\n" +
            "support\n" +
            "surf\n" +
            "surgery\n" +
            "suzuki\n" +
            "sv\n" +
            "swatch\n" +
            "swiss\n" +
            "sx\n" +
            "sy\n" +
            "sydney\n" +
            "systems\n" +
            "sz\n" +
            "tab\n" +
            "taipei\n" +
            "talk\n" +
            "taobao\n" +
            "target\n" +
            "tatamotors\n" +
            "tatar\n" +
            "tattoo\n" +
            "tax\n" +
            "taxi\n" +
            "tc\n" +
            "tci\n" +
            "td\n" +
            "tdk\n" +
            "team\n" +
            "tech\n" +
            "technology\n" +
            "tel\n" +
            "temasek\n" +
            "tennis\n" +
            "teva\n" +
            "tf\n" +
            "tg\n" +
            "th\n" +
            "thd\n" +
            "theater\n" +
            "theatre\n" +
            "tiaa\n" +
            "tickets\n" +
            "tienda\n" +
            "tips\n" +
            "tires\n" +
            "tirol\n" +
            "tj\n" +
            "tjmaxx\n" +
            "tjx\n" +
            "tk\n" +
            "tkmaxx\n" +
            "tl\n" +
            "tm\n" +
            "tmall\n" +
            "tn\n" +
            "to\n" +
            "today\n" +
            "tokyo\n" +
            "tools\n" +
            "top\n" +
            "toray\n" +
            "toshiba\n" +
            "total\n" +
            "tours\n" +
            "town\n" +
            "toyota\n" +
            "toys\n" +
            "tr\n" +
            "trade\n" +
            "trading\n" +
            "training\n" +
            "travel\n" +
            "travelers\n" +
            "travelersinsurance\n" +
            "trust\n" +
            "trv\n" +
            "tt\n" +
            "tube\n" +
            "tui\n" +
            "tunes\n" +
            "tushu\n" +
            "tv\n" +
            "tvs\n" +
            "tw\n" +
            "tz\n" +
            "ua\n" +
            "ubank\n" +
            "ubs\n" +
            "ug\n" +
            "uk\n" +
            "unicom\n" +
            "university\n" +
            "uno\n" +
            "uol\n" +
            "ups\n" +
            "us\n" +
            "uy\n" +
            "uz\n" +
            "va\n" +
            "vacations\n" +
            "vana\n" +
            "vanguard\n" +
            "vc\n" +
            "ve\n" +
            "vegas\n" +
            "ventures\n" +
            "verisign\n" +
            "versicherung\n" +
            "vet\n" +
            "vg\n" +
            "vi\n" +
            "viajes\n" +
            "video\n" +
            "vig\n" +
            "viking\n" +
            "villas\n" +
            "vin\n" +
            "vip\n" +
            "virgin\n" +
            "visa\n" +
            "vision\n" +
            "viva\n" +
            "vivo\n" +
            "vlaanderen\n" +
            "vn\n" +
            "vodka\n" +
            "volvo\n" +
            "vote\n" +
            "voting\n" +
            "voto\n" +
            "voyage\n" +
            "vu\n" +
            "wales\n" +
            "walmart\n" +
            "walter\n" +
            "wang\n" +
            "wanggou\n" +
            "watch\n" +
            "watches\n" +
            "weather\n" +
            "weatherchannel\n" +
            "web\n" +
            "webcam\n" +
            "weber\n" +
            "website\n" +
            "wed\n" +
            "wedding\n" +
            "weibo\n" +
            "weir\n" +
            "wf\n" +
            "whoswho\n" +
            "wien\n" +
            "wiki\n" +
            "williamhill\n" +
            "win\n" +
            "windows\n" +
            "wine\n" +
            "winners\n" +
            "wme\n" +
            "woodside\n" +
            "work\n" +
            "works\n" +
            "world\n" +
            "wow\n" +
            "ws\n" +
            "wtc\n" +
            "wtf\n" +
            "xbox\n" +
            "xerox\n" +
            "xihuan\n" +
            "xin\n" +
            "xxx\n" +
            "xyz\n" +
            "yachts\n" +
            "yahoo\n" +
            "yamaxun\n" +
            "yandex\n" +
            "ye\n" +
            "yodobashi\n" +
            "yoga\n" +
            "yokohama\n" +
            "you\n" +
            "youtube\n" +
            "yt\n" +
            "yun\n" +
            "za\n" +
            "zappos\n" +
            "zara\n" +
            "zero\n" +
            "zip\n" +
            "zm\n" +
            "zone\n" +
            "zuerich\n" +
            "zw\n";

    private static final String lIll =
            "世界\n" +
            "中信\n" +
            "中国\n" +
            "中國\n" +
            "中文网\n" +
            "亚马逊\n" +
            "企业\n" +
            "佛山\n" +
            "信息\n" +
            "健康\n" +
            "八卦\n" +
            "公司\n" +
            "公益\n" +
            "台湾\n" +
            "台灣\n" +
            "商城\n" +
            "商店\n" +
            "商标\n" +
            "嘉里\n" +
            "嘉里大酒店\n" +
            "在线\n" +
            "大拿\n" +
            "天主教\n" +
            "娱乐\n" +
            "家電\n" +
            "广东\n" +
            "微博\n" +
            "慈善\n" +
            "我爱你\n" +
            "手机\n" +
            "招聘\n" +
            "政务\n" +
            "政府\n" +
            "新加坡\n" +
            "新闻\n" +
            "时尚\n" +
            "書籍\n" +
            "机构\n" +
            "淡马锡\n" +
            "游戏\n" +
            "澳門\n" +
            "点看\n" +
            "移动\n" +
            "组织机构\n" +
            "网址\n" +
            "网店\n" +
            "网站\n" +
            "网络\n" +
            "联通\n" +
            "谷歌\n" +
            "购物\n" +
            "通販\n" +
            "集团\n" +
            "電訊盈科\n" +
            "飞利浦\n" +
            "食品\n" +
            "餐厅\n" +
            "香格里拉\n" +
            "香港\n";

    static String[] IIl1() {
        return lllI.split("\n");
    }

    static String[] l1lI() {
        return lIll.split("\n");
    }
}
